apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-container
          image: 043309346867.dkr.ecr.eu-north-1.amazonaws.com/argocd:latest
          ports:
            - containerPort: 3000
